"""Human-readable explanations for data-quality flags (shared by the UIs and reports)."""

FLAG_HELP = {
    "er_missing": "No engagement rate in the source file",
    "er_outlier_gt_15pct": "Engagement rate above 15% - check (viral spike, or data error)",
    "er_unparseable": "Engagement value could not be read",
    "topics_missing": "No category/topic in the source",
    "topics_unmapped_words": "Some topic words are not in the category vocabulary",
    "followers_missing": "No follower count",
    "followers_unparseable": "Follower value could not be read (e.g. 'lots')",
    "reach_unparseable": "Reach value could not be read",
    "name_case_fixed": "ALL CAPS / all lower-case name re-cased",
    "name_symbols_removed": "Emojis / symbols removed from the name",
    "name_unicode_folded": "Decorative Unicode font converted to plain letters",
    "name_spaced_letters_joined": "Spaced-out letters joined (F I L M Y -> Filmy)",
    "name_hashtags_removed": "Hashtags removed from the name",
    "name_non_latin_script": "Name contains a non-Latin script (kept as-is)",
    "name_unreadable": "Name had no readable letters - handle used instead",
    "name_from_handle": "No usable name - derived from the handle",
    "yt_handle_needs_resolution": "YouTube @handle not yet resolved to a channel ID (needs API)",
    "yt_username_needs_resolution": "Legacy YouTube /user/ URL not yet resolved (needs API)",
    "yt_custom_url_unresolvable": "YouTube /c/ URL - no cheap API lookup, needs manual check",
    "yt_resolved_via_api": "YouTube handle resolved to a channel ID via the API",
    "yt_channel_not_found": "YouTube API returned no channel for this ID",
    "categories_added_from_youtube": "Categories added from YouTube topic data",
    "url_params_stripped": "Tracking parameters removed from the URL",
    "exact_duplicate_rows_merged": "Several source rows were the same account and were merged",
    "conflicting_follower_counts": "Merged rows disagree on followers by more than 5%",
    "city_not_in_reference_list": "City not in the reference list - kept as typed",
    "post_url_not_profile": "Link points to a post, not a profile",
    "video_url_not_channel": "Link points to a video, not a channel",
    "rate_reel_range_midpoint": "Reel rate given as a range - midpoint used",
    "rate_story_range_midpoint": "Story rate given as a range - midpoint used",
    "rate_video_range_midpoint": "Video rate given as a range - midpoint used",
    "rate_reel_on_request": "Reel rate 'on request' / 'DM' - left empty",
    "rate_story_on_request": "Story rate 'on request' - left empty",
    "rate_video_on_request": "Video rate 'on request' - left empty",
    "rate_reel_unparseable": "Reel rate could not be read",
    "rate_story_unparseable": "Story rate could not be read",
    "rate_video_unparseable": "Video rate could not be read",
    "age_unparseable": "Age could not be read",
    "avg_views_unparseable": "Average views could not be read",
    "no_account_identifier": "No usable profile link or handle",
    "platform_unknown": "Can't tell which platform (bare @handle, no platform column)",
}
