"""Postgres (Supabase) backend with the same surface as the sqlite3 connections the app uses.

Set DATABASE_URL to switch the web app from SQLite files to Postgres. The SQL in the app stays
sqlite-flavoured ("?" placeholders, INTEGER/REAL types); this module translates it.

Each logical database lives in its own Postgres schema - "platform" for accounts/campaigns/billing,
"org_<id>" for each company's private creator data - so companies stay isolated the same way the
separate SQLite files kept them. Neither schema is "public", so Supabase's auto-generated REST API
(which exposes "public") never serves these tables.

The search_path is set with SET LOCAL at the start of every transaction rather than once per
connection, because Supabase's transaction pooler hands each transaction to whichever server
connection is free - session settings don't survive a commit.
"""
from __future__ import annotations

import re
import threading

import psycopg
from psycopg.adapt import Loader
from psycopg.pq import TransactionStatus

_SCHEMA_NAME = re.compile(r"^[a-z_][a-z0-9_]*$")
_ready: set[tuple[str, str]] = set()
_ready_lock = threading.Lock()


class Row(dict):
    """A row readable by column name (r["id"]) or position (r[0]), like sqlite3.Row.
    Positions come from the full column list, so two columns with the same name are both reachable."""

    __slots__ = ("_values",)

    def __init__(self, names, values):
        super().__init__()
        for n, v in zip(names, values):
            self.setdefault(n, v)  # by name, the first of duplicate names wins (as in sqlite3.Row)
        self._values = tuple(values)

    def __getitem__(self, key):
        if isinstance(key, int):
            return self._values[key]
        return super().__getitem__(key)


def _row_factory(cursor):
    names = [c.name for c in cursor.description or []]
    return lambda values: Row(names, values)


class _NumericLoader(Loader):
    """SUM() over integers returns NUMERIC; hand back int/float like SQLite does, not Decimal."""

    def load(self, data):
        s = bytes(data).decode()
        return float(s) if any(c in s for c in ".eE") or s in ("NaN", "Infinity", "-Infinity") else int(s)


def to_pg_sql(sql: str) -> str:
    """'?' placeholders -> '%s' (and literal '%' -> '%%'), leaving quoted strings alone."""
    out, quote = [], None
    for ch in sql:
        if quote:
            out.append("%%" if ch == "%" else ch)
            if ch == quote:
                quote = None
        elif ch in ("'", '"'):
            quote = ch
            out.append(ch)
        elif ch == "?":
            out.append("%s")
        elif ch == "%":
            out.append("%%")
        else:
            out.append(ch)
    return "".join(out)


def to_pg_ddl(ddl: str) -> str:
    ddl = re.sub(r"\bINTEGER PRIMARY KEY AUTOINCREMENT\b", "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY", ddl)
    ddl = re.sub(r"\bINTEGER\b", "BIGINT", ddl)   # follower/view counts can pass 2^31
    ddl = re.sub(r"\bREAL\b", "DOUBLE PRECISION", ddl)
    ddl = re.sub(r"\bBLOB\b", "BYTEA", ddl)
    return re.sub(r"\s+COLLATE NOCASE\b", "", ddl)  # emails are lower-cased before they're stored


class PgConnection:
    """Wraps a psycopg connection so app code can keep calling execute/executemany/commit/close."""

    is_postgres = True

    def __init__(self, url: str, schema: str):
        if not _SCHEMA_NAME.match(schema):
            raise ValueError(f"bad schema name {schema!r}")
        self.schema = schema
        # prepare_threshold=None: the transaction pooler can't keep prepared statements between transactions
        self._conn = psycopg.connect(url, prepare_threshold=None, row_factory=_row_factory, connect_timeout=15)
        self._conn.adapters.register_loader("numeric", _NumericLoader)

    def _begin_if_idle(self):
        if self._conn.info.transaction_status == TransactionStatus.IDLE:
            self._conn.execute(f'SET LOCAL search_path TO "{self.schema}"')

    def execute(self, sql: str, params=()):
        self._begin_if_idle()
        return self._conn.execute(to_pg_sql(sql), tuple(params)) if params else self._conn.execute(sql)

    def executemany(self, sql: str, seq):
        self._begin_if_idle()
        cur = self._conn.cursor()
        seq = [tuple(p) for p in seq]
        if seq:
            cur.executemany(to_pg_sql(sql), seq)
        return cur

    def commit(self):
        self._conn.commit()

    def rollback(self):
        self._conn.rollback()

    def close(self):
        self._conn.close()


def connect(url: str, schema: str, ddl: str) -> PgConnection:
    """Open a connection scoped to `schema`, creating the schema and its tables the first time this process sees it."""
    conn = PgConnection(url, schema)
    key = (url, schema)
    if key not in _ready:
        with _ready_lock:
            if key not in _ready:
                _create(conn, ddl)
                _ready.add(key)
    return conn


def _create(conn: PgConnection, ddl: str):
    for attempt in (1, 2):
        try:
            conn._conn.execute(f'CREATE SCHEMA IF NOT EXISTS "{conn.schema}"')
            conn._conn.execute(f'SET LOCAL search_path TO "{conn.schema}"')
            conn._conn.execute(to_pg_ddl(ddl))
            conn.commit()
            return
        except (psycopg.errors.UniqueViolation, psycopg.errors.DuplicateObject):
            # another server instance created the same schema at the same moment; its tables are there now
            conn.rollback()
            if attempt == 2:
                raise
